export const dataFromServer = {
  style: {
    record: 'ResumeStyle',
    colors: ['#000000', '#008CFF'],
    layout: 'double',
    layoutSize: 'medium',
    background: null,
    fontBody: 'interui',
    fontHeading: 'rubik',
    isMetaDataDisabled: false,
    marginOption: 1,
  },
  header: {
    record: 'Header',
    name: 'LD Khánh',
    title: 'LD CV',
    email: 'name@gmail.com',
    location: 'Lyon, France',
    phone: '+1-770-229-1908',
    link: 'youtube.com/channel/__NAME__',
    height: 168,
    showTitle: true,
    showPhone: true,
    showLink: true,
    showEmail: true,
    showLocation: true,
    uppercaseName: true,
    showPhoto: true,
    photoStyle: 'round',
    photo:
      'https://enhancv.s3.amazonaws.com/avatars/3016f4f91dc4340991e6391868fa8e81e9e774a49c29ca3d28c4159604ba1d7c.jpg',
  },
  coverLetterBuilderFields: {
    experience: 0,
    template: 'casual',
    skills: [],
    strengths: [],
    record: 'CoverLetterBuilderFields',
    position: '',
    name: '',
    emailAddress: '',
    phoneNumber: '',
    linkedIn: '',
  },
  record: 'Resume',
  version: 2,
  edits: 58,
  isCoverLetter: false,
  sections: [
    {
      record: 'AchievementSection',
      enabled: true,
      showIcons: false,
      name: 'Achievements',
      column: 0,
      height: 46,
      items: [
        {
          icon: '139-free-diamond-01',
          id: 'g5ncbasxy9',
          record: 'AchievementItem',
          title: 'Education Achievements',
          description: 'University Entrance Exam Score: 27.5/30',
          showDescription: true,
          height: 58,
        },

        {
          icon: '139-free-diamond-01',
          id: 'kp055lmi',
          record: 'AchievementItem',
          title: 'Telesale 4.0',
          description: 'Good marketing sale manager',
          showDescription: true,
          height: 58,
        },
        {
          icon: '139-free-diamond-01',
          id: 'xqpj2ltfnw',
          record: 'AchievementItem',
          title: 'Professional Achievements',
          description:
            'Revenue: USD 25,000\nBest salesman in 2 months consecutively',
          showDescription: true,
          height: 75,
        },
      ],
    },
    {
      record: 'CourseSection',
      enabled: true,
      name: 'Course',
      column: 0,
      height: 46,
      items: [
        {
          id: '73d7t15tft',
          record: 'CourseItem',
          title: 'API RP 14C and Safe Charting',
          description: 'Avalon Simulations and Process Consulting',
          height: 89,
          showDescription: true,
        },
        {
          id: 'syxce0no04',
          record: 'CourseItem',
          title: 'JAVA Standard Edition',
          description: 'New Horizon',
          height: 55,
          showDescription: true,
        },
        {
          id: 'izim215a',
          record: 'CourseItem',
          title: 'Microsoft SQL Server',
          description: 'New Horizon',
          height: 56,
          showDescription: true,
        },
      ],
    },
    {
      record: 'TechnologySection',
      enabled: true,
      name: 'Skills',
      column: 0,
      surroundingBorder: false,
      height: 51,
      items: [
        {
          tags: ['C++', 'Javascript', 'React'],
          id: 'b4yxsv0ph2',
          record: 'TechnologyItem',
          title: 'Technology',
          description: '',
          height: 62,
          showTitle: true,
        },
        {
          tags: ['C', 'NodeJs', 'C#'],
          id: 'b4yxsv0ph3',
          record: 'TechnologyItem',
          title: 'LD',
          description: '',
          height: 62,
          showTitle: true,
        },
      ],
    },
    {
      record: 'EducationSection',
      enabled: false,
      name: 'Education',
      column: 0,
      height: 46,
      timelineWidth: 136,
      items: [
        {
          bullets: [''],
          id: 'j6572top',
          record: 'EducationItem',
          degree: 'BACCALAURÉAT',
          institution: 'SCIENCES ECONOMIQUES',
          location: 'Lyon, France',
          gpa: '',
          gpaText: '',
          maxGpa: '',
          from: '',
          to: '',
          height: 82,
          showGpa: false,
          showLocation: false,
          showDateRange: true,
          showBullets: false,
        },
        {
          bullets: [''],
          id: 'h19b6da923',
          record: 'EducationItem',
          degree: 'Computers Engineering',
          institution: 'University X',
          location: 'Lyon, France',
          gpa: '',
          gpaText: '',
          maxGpa: '',
          from: '',
          to: '',
          height: 134,
          showGpa: true,
          showLocation: true,
          showDateRange: true,
          showBullets: true,
        },
      ],
    },
    {
      record: 'LanguageSection',
      enabled: false,
      name: '',
      column: 1,
      showProficiency: true,
      showSlider: true,
      indicatorType: 'dots',
      height: 46,
      items: [
        {
          id: 'lan7hbk0ni',
          record: 'LanguageItem',
          name: 'English',
          level: 5,
          levelText: '',
          height: 56,
        },
        {
          id: '.ybj7dzv6g',
          record: 'LanguageItem',
          name: 'TshiVenda',
          level: 5,
          levelText: '',
          height: 56,
        },
      ],
    },
    {
      record: 'ReferenceSection',
      enabled: false,
      name: '',
      column: 1,
      height: 36,
      items: [
        {
          id: 'ssl03304bo',
          record: 'ReferenceItem',
          name: 'OGUNLEWE Adeyinka',
          contact: 'adeyinka.ogunlewe@lasu.edu.ng\n+234-805-238-4753',
          height: 76,
          showContact: true,
        },
        {
          id: 'mbn1drzhm7',
          record: 'ReferenceItem',
          name: 'OYELA Ayodele',
          contact: 'ayodele.oyela@ng.kpmg.com\n+234-703-083-3525',
          height: 76,
          showContact: true,
        },
      ],
    },
    {
      record: 'ExperienceSection',
      enabled: true,
      name: 'Experience',
      column: 1,
      height: 48,
      timelineWidth: 136,
      items: [
        {
          bullets: [
            'Lead the UK internal audit and supported the 2014 budget creation',
            'Updated the internal Oracle Financial Software and Inventory project, increasing efficiency by 12%.',
          ],
          id: 'd2ip7toaao',
          record: 'ExperienceItem',
          position: 'IT Intern',
          workplace: 'Herman LLC',
          description:
            'Herman LLC is an energy trading company based in France',
          location: 'Lyon, France',
          from: '2018/11',
          to: '2020/11',
          link: '',
          height: 251,
          showTitle: true,
          showCompany: true,
          showDescription: true,
          showBullets: true,
          showLocation: true,
          showDateRange: true,
          showLink: false,
        },

        {
          bullets: [
            'Updated the internal Oracle Financial Software and Inventory project, increasing efficiency by 12%.',
            'Prepared a report for State Bank of Pakistan on Audit of Claimed\nTransactions of our client for past 5 years',
          ],
          id: 'kg5jpt37ul',
          record: 'ExperienceItem',
          position: 'IT Intern',
          workplace: 'Herman LLC',
          from: '2018/11',
          to: '2020/11',
          description:
            'Herman LLC is the largest natural gas transportation and distribution company in Indonesia',
          location: 'Lyon, France',
          link: '',
          height: 319,
          showTitle: true,
          showCompany: true,
          showDescription: true,
          showBullets: true,
          showLocation: true,
          showDateRange: true,
          showLink: false,
        },
      ],
    },
    {
      record: 'TalentSection',
      enabled: false,
      showIcons: false,
      name: '',
      column: 1,
      height: 46,
      items: [
        {
          icon: '23-free-star-two',
          id: 'loq3fbzy9n',
          record: 'TalentItem',
          title: 'Society of Petroleum Engineers',
          description: 'Professional Member (2015)',
          height: 87,
          showDescription: true,
        },
      ],
    },
    {
      record: 'ActivitySection',
      enabled: true,
      name: 'Activity',
      column: 1,
      height: 45,
      items: [
        {
          bullets: [''],
          id: 'u6kfkzh39f',
          record: 'ActivityItem',
          title: 'Project',
          location: '',
          from: '2021/12',
          to: '',
          link: '',
          description: '',
          height: 116,
          showDescription: true,
          showBullets: true,
          showTitle: true,
          showLocation: true,
          showDateRange: true,
          showLink: false,
        },
      ],
    },
    {
      record: 'VolunteerSection',
      enabled: true,
      name: 'Volunteer',
      column: 0,
      height: 51,
      items: [
        {
          bullets: [''],
          id: 'z4k0w7yvx9',
          record: 'VolunteerItem',
          role: '',
          institution: '',
          location: '',
          from: '',
          to: '',
          description: '',
          height: 100,
          showDescription: true,
          showLocation: false,
          showBullets: false,
          showDateRange: true,
        },
      ],
    },
    {
      record: 'SummarySection',
      enabled: true,
      name: 'Summary',
      column: 0,
      height: 51,
      items: [
        { id: 'ipfpaw489a', record: 'SummaryItem', text: '', height: 53 },
      ],
      showTitle: true,
    },
    {
      showSlider: true,
      record: 'SkillSection',
      enabled: true,
      name: 'Skill',
      column: 1,
      indicatorType: 'lolly',
      height: 79,
      items: [
        {
          icon: '21-free-star',
          id: 'rbletrcq9r',
          record: 'SkillItem',
          level: 2,
          name: 'PACK OFFICE: Word, Excel, PowerPoint, Acces',
          height: 84,
        },
        {
          icon: '21-free-star',
          id: 'ix19o207',
          record: 'SkillItem',
          level: 7,
          name: 'SQL et réseaux informatiques',
          height: 66,
        },
      ],
    },
  ],

  footer: 'www.enhancv.com',
  isImported: false,
  footerTexts: [],
  downloadCount: 0,
  mistakesCount: 9,
  stepProgress: 0,
  isLetterSize: false,
  careerCounselingResume: false,
  translationStatus: '',
  _id: '60a6b006e52510004a5ef940',
  user: '60a6b004001de5004a7fea1c',
  layout: [
    {
      record: 'LayoutItem',
      itemIndexes: [0, 1, 2],
      sectionIndex: 0,
      page: 0,
      column: 0,
      height: 251,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [0, 1, 2],
      sectionIndex: 1,
      page: 0,
      column: 0,
      height: 205,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [0],
      sectionIndex: 2,
      page: 0,
      column: 0,
      height: 127,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [0],
      sectionIndex: 10,
      page: 0,
      column: 0,
      height: 165,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [0],
      sectionIndex: 11,
      page: 0,
      column: 0,
      height: 118,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [0],
      sectionIndex: 5,
      page: 0,
      column: 1,
      height: 181,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [0, 1],
      sectionIndex: 6,
      page: 0,
      column: 1,
      height: 243,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [0, 1],
      sectionIndex: 8,
      page: 0,
      column: 1,
      height: 515,
    },
    {
      record: 'LayoutItem',
      itemIndexes: [2],
      sectionIndex: 8,
      page: 1,
      column: 1,
      height: 381,
    },
  ],
  editHistory: {
    '20/5/2021': 18,
    '21/5/2021': 31,
    '22/5/2021': 46,
    '23/5/2021': 57,
  },
  ignoredMistakes: [],
  title: 'IT Intern',
  userField: '',
  duplicatedFrom: null,
  coverLetterTemplate: '',
  createdAt: '2021-05-20T18:52:54.509Z',
  updatedAt: '2021-05-22T21:49:00.356Z',
  __v: 57,
  id: '60a6b006e52510004a5ef940',
};
